site_name: SEC Web Scraper
site_url: https://deji725.github.io/sec-web-scraper
repo_url: https://github.com/deji725/sec-web-scraper
repo_name: deji725/sec-web-scraper
site_description: A web scraper for SEC EDGAR filings
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: lime


nav:
- Home:
  - Overview: index.md
  - License: license.md
    #- User Guide:
    #- Usage Examples: examples/
    #- API Reference: reference/
- Development:
  - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/deji725
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/deji/

markdown_extensions:
  - markdown_include.include
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
    

plugins:
  - search
  - mkdocstrings
